#!/usr/bin/env python3
"""Turn data/project_numbers.json into LaTeX macros, so the paper cites numbers
instead of typing them.

Every \\dataref{key} in the paper resolves to a macro defined here. A key that does not
exist in the registry fails the build rather than printing something plausible, which is
the point: a number in the paper that nothing computed cannot survive a rebuild.

Run:  .venv/bin/python scripts/make_numbers_tex.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "data" / "project_numbers.json"
OUT = ROOT / "paper" / "generated_numbers.tex"

# How many significant figures each unit is allowed to show. Nothing is quoted finer
# than it was measured.
PLACES = {"per cent": 2, "fraction": 5, "dimensionless": 4, "relative": 3,
          "per second": 4, "templates": 0}


def fmt(value, unit):
    if unit == "templates":
        return f"{int(round(value))}"
    if unit in ("relative", "per second"):
        # plain math rather than siunitx: the installed TeX is
        # texlive-latex-recommended, which does not ship siunitx, and the paper must
        # build on the machine that will be asked to rebuild it
        mantissa, exponent = f"{value:.4g}".split("e") if "e" in f"{value:.4g}" \
            else (f"{value:.4g}", None)
        if exponent is None:
            return mantissa
        # no $ delimiters: the paper uses these inside math, and emitting our own
        # would nest $...$ inside $...$ and break the build
        return f"{mantissa} \\times 10^{{{int(exponent)}}}"
    return f"{value:.{PLACES.get(unit, 4)}f}"


def main():
    registry = json.loads(REGISTRY.read_text())
    lines = ["% Generated by scripts/make_numbers_tex.py -- do not edit.",
             "% Registry keys use underscores; macro names use hyphens, because an",
             "% underscore in the argument of \\dataref would be read as a subscript.",
             "% Source: data/project_numbers.json, written by scripts/compute_numbers.py.",
             "\\makeatletter",
             "\\newcommand{\\dataref}[1]{%",
             "  \\ifcsname dataref@#1\\endcsname\\csname dataref@#1\\endcsname",
             "  \\else\\GenericError{}{Unknown \\string\\dataref{#1}}{}{}\\fi}",
             ""]
    for key in sorted(registry):
        record = registry[key]
        lines.append(f"\\expandafter\\def\\csname dataref@{key.replace(chr(95), chr(45))}\\endcsname"
                     f"{{{fmt(record['value'], record['unit'])}}}")
    lines += ["\\makeatother", ""]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(registry)} macros)")


if __name__ == "__main__":
    main()
